import Head from "next/head";
import {useDispatch} from "react-redux";
import {useEffect} from "react";
import axios from "axios";
import {setData} from "@/redux/reducers/content";

export default function Home() {
    const dispatch = useDispatch();
    // const {users} = useSelector((state) => state.content);

    useEffect(() => {
        axios.get("https://jsonplaceholder.typicode.com/todos")
            .then((res) => dispatch(setData(res.data)))
            .catch((err) => console.log('ERR ---> ', err))
    },[]);

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={`main`}>

            </main>
        </>
    );
}
