import Head from "next/head";
import {useDispatch} from "react-redux";
import {useEffect} from "react";
import content, {setPage, useContent} from "@/redux/reducers/content";
import Authorization from "@/components/authorization/Authorization";
import {CSSTransition, SwitchTransition} from "react-transition-group";
import Game from "@/components/game/Game";
import {formContent} from "@/constants/content";

export default function Home() {
    const dispatch = useDispatch();
    const {page} = useContent();

    const component = {
        authorization: <Authorization {...formContent}/>,
        game: <Game/>
    }

    useEffect(() => {
        // console.log('FQQESE');
        dispatch(content.thunks.getData());
        const user = JSON.parse(window?.localStorage?.getItem('user'));
        if (user) dispatch(setPage('game'));
    },[]);


    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={`main`}>
                <SwitchTransition>
                    <CSSTransition key={page} timeout={300} classNames={'page'}>
                        <section className={'page'}>
                            {component[page]}
                        </section>
                    </CSSTransition>
                </SwitchTransition>
            </main>
        </>
    );
}
